// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtOStLK6LzwGBbHVDknOl2AJgqvwRGEyw',
    appId: '1:833939946288:web:a6beebc8073602bf3e66f5',
    messagingSenderId: '833939946288',
    projectId: 'chatapp-8318c',
    authDomain: 'chatapp-8318c.firebaseapp.com',
    storageBucket: 'chatapp-8318c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBitcgaz6r__1j0i4txhERgqxBORsibce4',
    appId: '1:833939946288:android:b961ab9be0fbc2583e66f5',
    messagingSenderId: '833939946288',
    projectId: 'chatapp-8318c',
    storageBucket: 'chatapp-8318c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVG6vb55RMJvWWju26WF-EQkRwvw3CDlw',
    appId: '1:833939946288:ios:7a3762a5ea58c71e3e66f5',
    messagingSenderId: '833939946288',
    projectId: 'chatapp-8318c',
    storageBucket: 'chatapp-8318c.appspot.com',
    androidClientId: '833939946288-btvtg63uilid6ju25au5b4oucd43o157.apps.googleusercontent.com',
    iosClientId: '833939946288-5u02kli80mck6638g7p9ifg15005vm6h.apps.googleusercontent.com',
    iosBundleId: 'com.rafouniq.chatapp',
  );
}
